#!/bin/bash
#
# Copyright (c) 2010, 2013, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR commonsense.A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#
PROG_NAME="${BASH_SOURCE[0]}"
while [ -h "${PROG_NAME}" ]; do
  PROG_NAME="$(readlink "${PROG_NAME}")"
done
SCRIPT_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"

echo " Welcome to Landz!"

echo "   __         ______     __   __     _____     ______    "
echo "  /\ \       /\  __ \   /\ \-.\ \   /\  __-.  /\___  \   "
echo "  \ \ \____  \ \  __ \  \ \ \-.  \  \ \ \/\ \ \/_/  /__  "
echo "   \ \_____\  \ \_\ \_\  \ \_\-.\_\  \ \____-   /\_____\ "
echo "    \/_____/   \/_/\/_/   \/_/ \/_/   \/____/   \/_____/ "

echo " "
echo " Landz, 1.0.0-20130405"



java -server -XX:-TieredCompilation -Xms128M -Xmx2G -esa -ea -cp $SCRIPT_DIR/../out/production/landz.zee -XX:+HeapDumpOnOutOfMemoryError -Djava.lang.invoke.MethodHandle.DEBUG_NAMES=false -Dnashorn.debug=true z.zee.Z $*
