#!/bin/sh

PROG_NAME="${BASH_SOURCE[0]}"
while [ -h "${PROG_NAME}" ]; do
  PROG_NAME="$(readlink "${PROG_NAME}")"
done
SCRIPT_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"

echo " Welcome to Landz!"

echo "   __         ______     __   __     _____     ______    "
echo "  /\ \       /\  __ \   /\ \-.\ \   /\  __-.  /\___  \   "
echo "  \ \ \____  \ \  __ \  \ \ \-.  \  \ \ \/\ \ \/_/  /__  "
echo "   \ \_____\  \ \_\ \_\  \ \_\-.\_\  \ \____-   /\_____\ "
echo "    \/_____/   \/_/\/_/   \/_/ \/_/   \/____/   \/_____/ "

echo " "
echo " Landz, 1.0.0-20130421"



java -server -XX:-TieredCompilation -Xms128M -Xmx2G -esa -ea -cp $SCRIPT_DIR/../out/production/landz.zee -XX:+HeapDumpOnOutOfMemoryError -Djava.lang.invoke.MethodHandle.DEBUG_NAMES=false -Dnashorn.debug=true z.zee.Z -scripting
